name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Job Triggered with this event: ${{ github.event_name }}"
          echo "Repo branch in use is this ${{ github.ref }}"

      - uses: actions/checkout@v3.3.0

      - name: List files in repo
        run: |
          echo "Repo ${{ github.repository }} as this files:"
          tree
